## general
last_page_empty: True
grid_month: True
title_month: True

## texts
months:
    jan: Janvier
    feb: Février
    mar: Mars
    apr: Avril
    may: Mai
    jun: Juin
    jul: Juillet &nbsp&nbsp
    aug: Août &nbsp&nbsp
    sep: Septembre
    oct: Octobre
    nov: Novembre
    dec: Décembre
days:
    mon: lun
    tue: mar
    wed: mer
    thu: Jeu
    fri: ven
    sat: sam
    sun: dim
headers:
    left_col: perso
    right_col: boulot
    box_left_page: priorités
    box_right_page: thèse sur la semaine

## css
line_size: 1px
font:
    name: JaneAusten
    file: jane_austen/JaneAust.ttf
font_size:
    week_title: 25px
    month_title: 50px
    month_grid: 15px
    dates: 17px
    events: 15px
page:
    width: 165mm
    height: 215mm
    display_borders: False
    alternate_align: True
    padding:
        top: 0.5cm
        bot: 0.5cm
        inner_side: 1.3cm
        outer_side: 0.6cm
month_grid:
    width: 80%
    height: 80%
spacing:
    collumn_title:
        top: 0mm  # is used in a calc so unit is required
        padding: 0
    week_title:
        top: 1cm
        left: 0.5cm
    month_title:
        top: 2cm
    box:
        top: 1%
        right: 0%
        bot: 7%
        left: 0%
    month_grid:
        top: 1.5cm
        right: 0
        bot: 0.5cm
        left: 0
        cell:
            top: 0mm
            left: 1mm
    week_cell:
        top: 0mm
        left: 2mm


## moons
moon:
    enable: True
    color: '#571805'
    opacity: 1
    align: top  # top or bottom
    padding: 2mm
    size: 7.5mm
    full:
        enable: True
        image: howling_wolf.png
    new:
        enable: True
        image: sleeping_fox.png


## events
events:
    custom:
        enable: True
        yaml: events.yaml
    holidays:
        enable: True
        country: fr
        use_names: True
        lang: fr
        custom_text: Férié
    color: '#571805'
    opacity: 1
    align: center
    padding:
        top: 3mm
        sides: 10%
