## general
last_page_empty: True
grid_month: True
title_month: True

## texts
months:
    jan: Janvier
    feb: Février
    mar: Mars
    apr: Avril
    may: Mai
    jun: Juin
    jul: Juillet &nbsp&nbsp
    aug: Août &nbsp&nbsp
    sep: Septembre
    oct: Octobre
    nov: Novembre
    dec: Décembre
days:
    mon: lun
    tue: mar
    wed: mer
    thu: Jeu
    fri: ven
    sat: sam
    sun: dim
headers:
    left_col: perso
    right_col: boulot
    box_left_page: priorités
    box_right_page: thèse sur la semaine

## css
line_size: 1px
font: JaneAusten
font_size:
    week_title: 30px
    month_title: 50px
    body: 20px
page:
    width: 100%
    height: 100%
    display_borders: False
    padding:
        top: 1cm
        bot: 0.5cm
        inner_side: 2cm
        outer_side: 1cm
month_grid:
    width: 80%
    height: 80%
spacing:
    week_title:
        top: 20%
        left: 0
    month_title:
        top: 2cm
    box:
        top: 2%
        right: 3%
        bot: 7%
        left: 0%
    month_grid:
        top: 1.5cm
        cell:
            top: 2%
            left: 6%
