days:
    mon: 'lun'
    tue: 'mar'
    wed: 'mer'
    thu: 'Jeu'
    fri: 'ven'
    sat: 'sam'
    sun: 'dim'
headers:
    left_col: 'perso'
    right_col: 'boulot'
    box_left_page: 'priorités'
    box_right_page: 'thèse sur la semaine'
